<html>


<!-- Mirrored from www.jefferypsanders.com/autolispintr_ent.html by HTTrack Website Copier/3.x [XR&CO'2004], Thu, 23 Sep 2004 01:07:54 GMT -->
<head>
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="description" content="Autolisp Entity Functions.">
<meta name="keywords" content="autolisp entity functions, autolisp functions, entget, entupd, entlast, entnext, entdel, entmod">
<title>The AutoLisp Intermediate Tutorial - Entity Functions</title>
</head>

<body>

<p align="center"><font color="#000000"><big><big><big><strong>The
    AutoLisp Intermediate Tutorial</strong></big></big></big></font><font face="Helvetica"></p>
    </font><hr size="4" color="#0000FF">
    <p><u><big><big><strong>Entity Functions</strong></big></big></u></p>
    <p><big><strong>&nbsp;&nbsp; <a href="#entget">entget</a>&nbsp;&nbsp; <a href="#entlast">entlast</a>&nbsp;&nbsp;&nbsp;
    <a href="#entnext">entnext</a> &nbsp;&nbsp;&nbsp; <a href="#entdel">entdel</a>&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="#entmod">entmod</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="#entupd">entupd</a>&nbsp;
    &nbsp; <a href="autolispintr_ent.html#Example">Example Program</a></strong></big></p>
    <hr size="4" color="#0000FF">
    <p><big><strong>&nbsp; <a name="entget">entget</a></strong></big> - This function returns
    the DXF Group Codes of the entity.</p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Syntax : <strong>(entget
    ename)</strong></p>
    <p align="left"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ename </strong>- a valid entity name returned by entsel, ssname, entlast, or the entnext
    &nbsp; function.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>Returns</strong>
    an Entity's DXF Group Codes as an association list.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(setq en(car(entsel)))</font> returns entity name as
    eg. &lt;Entity name: 3b40a60&gt;</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(entget en)</font> returns :</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ((-1 . &lt;Entity name: 3b40a60&gt;) (0 . &quot;LINE&quot;) (5 . &quot;FC&quot;) (100 .
    &quot;AcDbEntity&quot;) (67 . 0) (8 . &quot;DIM&quot;)
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    (100 . &quot;AcDbLine&quot;) (10 252.578 68.25 0.0) (11 188.379 31.5 0.0) (210 0.0 0.0
    1.0))</p>
    <p align="left">&nbsp;</p>
    <p><big><strong>&nbsp; <a name="entlast">entlast</a></strong></big> - This function
    returns the name of the last non-deleted entity in the drawing. </p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Syntax : <strong>(entlast)</strong></p>
    <p align="left"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </strong>This function is mainly used to get the last entity added to the drawing.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>Returns</strong>
    an entity name.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(entlast)</font> returns &lt;Entity name: 3b40a60&gt;</p>
    <p align="left">&nbsp;</p>
    <p><big><strong>&nbsp; <a name="entnext">entnext</a></strong></big> - Let's look at
    AutoDesk's explanation: &nbsp; If entnext is called with no arguments, it returns the
    entity name
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    of the first nondeleted entity in the database. If entnext is called with an entity name
    argument ename, it
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    returns the entity name of the first nondeleted entity following ename in the database. If
    there is no next
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    entity in the database, it returns nil. The entnext function returns both main entities
    and subentities.<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    The entities selected by ssget are main entities, not attributes of blocks or vertices of
    polylines. You can
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    access the internal structure of these complex entities by walking through the subentities
    with entnext.
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Once you obtain a subentity's name, you can operate on it like any other entity. If you
    obtain the name
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    of a subentity with entnext, you can find the parent entity by walking forward with
    entnext until a seqend
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    entity is found, then extracting the -2 group from that entity, which is the main entity's
    name. </p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Syntax : <strong>(entnext)
    &nbsp; or (entnext ename)</strong></p>
    <p align="left"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ename </strong>- a valid entity name returned by entsel, ssname, entlast, or the entnext
    function.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(entnext)</font> returns the name of the first entity
    in the drawing.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(entnext ename)</font> returns the name of the next
    entity following ename.</p>
    <p align="left">&nbsp;</p>
    <p><big><strong>&nbsp; <a name="entdel">entdel</a></strong></big> - This function deletes
    an entity from the drawing if it exist.&nbsp; If it does not exist and has been previously
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    deleted, it will undelete the entity.&nbsp; </p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Syntax : <strong>(entdel
    ename)</strong></p>
    <p align="left"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ename </strong>- a valid entity name returned by entsel, ssname, entlast, or the entnext
    function.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>Returns</strong>
    an entity name.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(setq en(car(entsel)))</font> returns the name of
    selected entity.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(entdel en)</font> deletes the entity and returns the
    name of the deleted entity.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(entdel en)</font> undeletes the entity and returns
    the name of the undeleted entity.</p>
    <p>&nbsp;</p>
    <p><big><strong>&nbsp; <a name="entmod">entmod</a></strong></big> - Modifies an entity in
    the AutoCAD database.&nbsp; </p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Syntax : <strong>(entmod
    elist)</strong></p>
    <p align="left"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    elist </strong>- a list that is returned from an entget statement. (DXF Group Codes of an
    entity)</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>Returns</strong>
    an elist if successful otherwise it returns nil.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(setq en(car(entsel)))</font> returns the name of
    selected entity.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(setq elist(entget en))</font> returns the DXF Group
    Codes of the entity.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(setq elist(subst (cons 8 &quot;DIM&quot;)(assoc 8
    elist) enlist)) </font></p>
    <p align="left"><font color="#FF0000" face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </font>The line above Replaces existing layer name in the elist with new layer name
    &quot;DIM&quot;</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(entmod elist) </font>updates the AutoCAD database
    and replaces the old layer name with the new one.</p>
    <p align="left"><font color="#FF0000" face="Courier">&nbsp; </font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </p>
    <p><strong><big>&nbsp; <a name="entupd">entupd</a></big> </strong>- Updates the screen
    image of an entity.</p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Syntax : <strong>(entupd
    ename)</strong></p>
    <p align="left"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ename </strong>- a valid entity name returned by entsel, ssname, entlast, or the entnext
    function.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>Returns</strong>
    an entity name.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(setq en(car (entsel)))</font> returns an entity
    name.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(entupd ename)</font> refreshes the entity on the
    graphics screen.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Note:&nbsp; If you modify the DXF Group Codes of an entity, such as changing the layer (8
    . &quot;LAyerName&quot;), you
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; will
    not notice the change until you regenerate the entire drawing or use entupd to regenerate
    the entity. </p>
    <p align="left">&nbsp;</p>
    <p align="left"><strong>End of Entity Functions</strong></p>
    <hr size="4" color="#0000FF">
    <p align="left"><strong><a name="Example">Example</a> Program 1:</strong></p>
    <p align="left">Let's change an entity's layer to a layer named &quot;DIM&quot;.</p>
    <p align="left"><font face="Courier">(defun C:CLay()</font></p>
    <p align="left"><font face="Courier">&nbsp; (if(setq ent(entsel))</font></p>
    <p align="left"><font face="Courier">&nbsp;&nbsp;&nbsp; (progn</font></p>
    <p align="left"><font face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq en(car ent)) </font></p>
    <p align="left"><font face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq enlist(entget
    en))</font></p>
    <p align="left"><font face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq enlist (subst
    (cons 8 &quot;Dim&quot;)(assoc 8 enlist)enlist))</font></p>
    <p align="left"><font face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (entmod enlist)</font></p>
    <p align="left"><font face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (entupd en)</font></p>
    <p align="left"><font face="Courier">&nbsp;&nbsp;&nbsp; )</font></p>
    <p align="left"><font face="Courier">&nbsp;&nbsp;&nbsp; (alert &quot;Error - Select an
    entity please.&quot;)</font></p>
    <p align="left"><font face="Courier">&nbsp; )</font></p>
    <p align="left"><font face="Courier">&nbsp; (princ)</font></p>
    <p align="left"><font face="Courier">)&nbsp; </font></p>
    <p align="left"><strong>Execution:</strong></p>
    <p align="left"><font face="Courier">Command: (load &quot;CLay&quot;)&lt;enter&gt;</font></p>
    <p align="left"><font face="Courier">Command: CLay&lt;enter&gt;</font></p>
    <p align="left"><font face="Courier">Command:&nbsp; Select Object:&lt;pick&gt;</font></p>
    <p align="left"><font face="Courier">Command: </font></p>
    <hr size="4" color="#0000FF">
    <p align="center"><a href="autolispintr.html">AutoLisp Intermediate Tutorial</a></p>
    <p align="center"><a href="index.html">AutoLisp Tutorial Home</a></p>
</body>

</html>
