<html>


<!-- Mirrored from www.jefferypsanders.com/autolisp_DCL_Part7.html by HTTrack Website Copier/3.x [XR&CO'2004], Thu, 23 Sep 2004 01:10:04 GMT -->
<head>
<meta name="description" content="AutoLisp Dialog Control Language">
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="keywords" content="autolisp, DCL, dialog, control, language">
<title>The AutoLisp Ultimate Tutorial&nbsp; - DCL</title>
</head>

<body>

<p align="center"><font color="#000000"><big><big><big><strong>The
    AutoLisp Tutorial - DCL</strong></big></big></big></font><font face="Helvetica"></p>
    </font><p align="center"><font color="#000000"><big><big><strong>Dialog Control Language -
    Part 7</strong></big></big></font></p>
    <hr size="4" color="#0000FF">
    <p>&nbsp;&nbsp; Now it is time to take all of the parts and pieces and put them together.
    &nbsp; Let's build a working DCL file that will let us see most of the things we've
    learned and yet not get to deep into autolisp. </p>
    <p>&nbsp; Lets draw a polygon or circle, on a selected layer with the option to save the
    settings last used for defaults next time we run the program.&nbsp; If polygon is chosen,
    ask for the number of sides.&nbsp; So....we will need a list_box to hold all of the
    available layer names.&nbsp; We will need a radio_column to select a circle or polylgon.
    &nbsp; We will need an popup_list to hold the number of sides for the polygon.&nbsp; We
    will need a toggle to check the &quot;Save Settings&quot; option.&nbsp; And last, we will
    need an Okay and Cancel button.</p>
    <hr size="4" color="#0000FF">
    <p>&nbsp; <strong>Layout thoughts:&nbsp;</strong> The list will need to have several
    layers showing so the user won't have to scroll forever.&nbsp; So, it will&nbsp; probably
    be the tallest item on the dialog box.&nbsp; I'll put it in a column by itself.&nbsp; I'll
    try to fit the rest of the items in a column beside it.&nbsp; Then I'll put the Okay and
    Cancel buttons at the bottom in a row.&nbsp; So...I'll need something like this:</p>
    <p><font face="Courier New">: column { <br>
    &nbsp; : row { <br>
    &nbsp;&nbsp;&nbsp; : boxed_column { <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : radio_column&nbsp; { <br>
    &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; : radio_button { </font></p>
    <p><font face="Courier New">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Put
    code for radio button 1 here [ Circle ]<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }&nbsp; <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : radio_button { </font></p>
    <p><font face="Courier New">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Put
    code for radio button 2 here [ Polygon ]<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }&nbsp; <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }&nbsp; <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : popup_list { </font></p>
    <p><font face="Courier New">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Put code
    for popup_list here [ Number of Sides ]<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }&nbsp;&nbsp; <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : toggle { </font></p>
    <p><font face="Courier New">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Put code
    for toggle here&nbsp; [ Save Settings ]<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }&nbsp;&nbsp; <br>
    &nbsp;&nbsp;&nbsp; }&nbsp; <br>
    &nbsp;&nbsp;&nbsp; : row&nbsp; { <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : list_box { </font></p>
    <p><font face="Courier New">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Put code
    for list here [ Layer Names ]<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }&nbsp; <br>
    &nbsp;&nbsp;&nbsp; }&nbsp; <br>
    &nbsp; }<br>
    &nbsp; : row { <br>
    &nbsp;&nbsp;&nbsp; : button { </font></p>
    <p><font face="Courier New">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Put code for button 1
    here [ Okay ]<br>
    &nbsp;&nbsp;&nbsp; } <br>
    &nbsp;&nbsp;&nbsp; : button { </font></p>
    <p><font face="Courier New">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // Put code for button 2
    here [ Cancel ]<br>
    &nbsp;&nbsp;&nbsp; } <br>
    &nbsp; }&nbsp;&nbsp; <br>
    } </font></p>
    <hr size="4" color="#0000FF">
    <p>Let's copy in the code for the header and all of the controls above.&nbsp; I'll show
    them in red.&nbsp; Notice the key names and labels had to be changed.</p>
    <p><font color="#FF0000"><font face="Courier New">SAMPLE7 : dialog { <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; label = &quot;Sample Dialog Box Routine -
    Part 7&quot;;</font> </font><br>
    <font face="Courier New">&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : column { <br>
    &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; : row { <br>
    &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; : boxed_column { <br>
    &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
    radio_column&nbsp; { </font><br>
    <font face="Courier New"><font color="#FF0000">&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    key = &quot;radios&quot;;<br>
    </font>&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    : radio_button {<br>
    <font color="#FF0000">&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    label = &quot;Draw Circle&quot;;<br>
    &nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    key = &quot;drawcir&quot;;<br>
    &nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    value = &quot;1&quot;;</font><br>
    &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }&nbsp; <br>
    &nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    : radio_button {<br>
    <font color="#FF0000">&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    label = &quot;Draw Polygon&quot;;<br>
    &nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    key = &quot;drawpol&quot;;<br>
    &nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    value = &quot;0&quot;;</font><br>
    &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }&nbsp; <br>
    &nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }&nbsp; <br>
    &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
    popup_list {<br>
    <font color="#FF0000">&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    key = &quot;numsides&quot;;<br>
    &nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    label = &quot;Number of Sides&quot;;<br>
    &nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    width = 25;</font></font> <br>
    <font face="Courier New">&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000">fixed_width_font = true;</font><br>
    &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>
    &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
    toggle { <br>
    <font color="#FF0000">&nbsp; &nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; key =
    &quot;saveset&quot;; <br>
    &nbsp;
    &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    label = &quot;Save settings&quot;; </font><br>
    &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>
    &nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }&nbsp; <br>
    &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : row&nbsp; { <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
    list_box {<br>
    <font color="#FF0000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; label =&quot;Select
    Layer&quot;;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; key =
    &quot;layerList&quot;;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; height = 5;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; width = 15;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; multiple_select =
    false;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; fixed_width_font =
    true;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; value = &quot;&quot;;</font><br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }&nbsp; <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; : row { <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : button {<br>
    <font color="#FF0000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; key = &quot;accept&quot;;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    label = &quot; Okay &quot;;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    is_default = true;</font><br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : button {<br>
    <font color="#FF0000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; key = &quot;cancel&quot;;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    label = &quot; Cancel &quot;;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    is_default = false;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    is_cancel = true;</font><br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }&nbsp;&nbsp; <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; } </font></p>
    <p><font face="Courier New">}</font></p>
    <p><strong>Right click and copy the above. Open NotePad and paste it.&nbsp; Save the file
    as SAMPLE.DCL&nbsp; <em>Be sure to change the &quot;Save as Type&quot; drop down box to
    &quot;All Files&quot; before saving it or it will put a&nbsp; &quot;.txt&quot; extension
    on the file name.&nbsp; Save this file somewhere in the AutoCAD search path.</em></strong></p>
    <hr size="4" color="#0000FF">
    <p>&nbsp; Next we will get a copy of the AutoLisp model and revise it.&nbsp; All new code
    is shown in red.</p>
    <p><small><font face="Courier New">(defun C:<font color="#FF0000">SAMPLE7</font>()<br>
    <br>
    &nbsp; ;;;--- Load the dcl file<br>
    &nbsp; (setq dcl_id (load_dialog &quot;<font color="#FF0000">SAMPLE7</font>.dcl&quot;))<br>
    <br>
    &nbsp; ;;;--- Load the dialog definition if it is not already loaded<br>
    &nbsp; (if (not (new_dialog &quot;<font color="#FF0000">SAMPLE7</font>&quot; dcl_id) )
    (exit))<br>
    <br>
    &nbsp; ;;;--- If an action event occurs, do this function<br>
    &nbsp; (action_tile &quot;cancel&quot; &quot;(setq ddiag 1)(done_dialog)&quot;)<br>
    &nbsp; (action_tile &quot;accept&quot; &quot;(setq ddiag 2)(saveVars)(done_dialog)&quot;) <br>
    <br>
    &nbsp; ;;;--- Display the dialog box<br>
    &nbsp; (start_dialog)</font></small></p>
    <p><small><font face="Courier New">&nbsp; ;;;--- Unload the dialog box<br>
    &nbsp; (unload_dialog dcl_id)<br>
    <br>
    &nbsp; ;;;--- If the cancel button was pressed - display message<br>
    &nbsp; (if (= ddiag 1)<br>
    &nbsp;&nbsp;&nbsp; (princ &quot;\n \n ...<font color="#FF0000">SAMPLE7</font> Cancelled.
    \n &quot;)<br>
    &nbsp; )<br>
    <br>
    &nbsp; ;;;--- If the &quot;Okay&quot; button was pressed<br>
    &nbsp; (if (= ddiag 2)<br>
    &nbsp;&nbsp;&nbsp; (princ &quot;\n \n ...<font color="#FF0000">SAMPLE7</font>
    Complete!&quot;)<br>
    &nbsp; )<br>
    <br>
    &nbsp; ;;;--- Suppress the last echo for a clean exit<br>
    &nbsp; (princ)<br>
    <br>
    ) </font></small></p>
    <p><strong>Right click and copy the above. Open NotePad and paste it.&nbsp; Save the file
    as SAMPLE7.LSP&nbsp; <em>Be sure to change the &quot;Save as Type&quot; drop down box to
    &quot;All Files&quot; before saving it or it will put a&nbsp; &quot;.txt&quot; extension
    on the file name.&nbsp; Save this file somewhere in the AutoCAD search path.</em></strong></p>
    <hr size="4" color="#0000FF">
    <p>&nbsp; Let's load the program and see what the DCL file looks like.&nbsp; On the
    command line type this:</p>
    <p>Command: (load &quot;sample7&quot;) and press enter</p>
    <p>&nbsp; You should see this</p>
    <p>C:Sample7 <br>
    Command:</p>
    <p>&nbsp; Now type Sample and press enter.&nbsp; If everything went according to plan you
    should see this on your screen:</p>
    <p>&nbsp;</p>
    <p align="center">
    <img src="images/DCL_PART701.jpg" alt="DCL_PART101.jpg (13229 bytes)" WIDTH="368" HEIGHT="185"></p>
    <p align="left">&nbsp; Notice there are no items in either list.&nbsp; We haven't added
    that part yet.&nbsp; Also notice the Draw Circle is selected.&nbsp; We did that in the DCL
    file. We set the value of that radio_button to &quot;1&quot;.&nbsp;&nbsp; We did not set
    the value of the toggle, so the default is unchecked.&nbsp; </p>
    <p align="left">&nbsp; If you push the Cancel button the program will exit normally.
    &nbsp; If you press the Okay button an error will occur because we have not defined the
    saveVars routine.</p>
    <p align="left">&nbsp; We have two things left to do.&nbsp; First we need to build the
    list for the popup_list control and the list_box control.&nbsp; Then we need to add the
    list to the dialog box.</p>
    <hr size="4" color="#0000FF">
    <p>&nbsp; Instead of building a function to get all of the layer names into a list, let's
    just build the list manually to keep things simple.&nbsp; Okay...you talked me into it.
    &nbsp; I'll do it both ways and you can use the one you want.&nbsp; I'm going to use the
    short version for this tutorial.</p>
    <p>Long way:</p>
    <p><small><font face="Courier New">&nbsp; ;;;--- Set up a list to hold the layer names<br>
    &nbsp; (setq layerList(list))<br>
    <br>
    &nbsp; ;;;--- Get the first layer name in the drawing<br>
    &nbsp; (setq layr(tblnext &quot;LAYER&quot; T))<br>
    <br>
    &nbsp; ;;;--- Add the layer name to the list<br>
    &nbsp; (setq layerList(append layerList (list(cdr(assoc 2 layr)))))<br>
    <br>
    &nbsp; ;;;--- Step though the layer table to get all layers<br>
    &nbsp; (while (setq layr(tblnext &quot;LAYER&quot;))<br>
    <br>
    &nbsp;&nbsp;&nbsp; ;;;--- Save each layer name in the list<br>
    &nbsp;&nbsp;&nbsp; (setq layerList(append layerList (list(cdr(assoc 2 layr)))))<br>
    &nbsp; )<br>
    </font></small></p>
    <p>Short Way:&nbsp; </p>
    <p><small><font face="Courier New">(setq layerList(list &quot;0&quot; &quot;DIM&quot;
    &quot;HIDDEN&quot; &quot;STR&quot; &quot;TX&quot; &quot;WELD&quot;))</font></small></p>
    <p>We also need a list for the polgon's number of sides:</p>
    <p><small><font face="Courier New">(setq numSides(list &quot;4&quot; &quot;6&quot;
    &quot;8&quot; &quot;12&quot; &quot;16&quot;))</font></small></p>
    <p>We need to add these lines to our autolisp program.&nbsp; Add it just below the
    new_dialog call and above the action_tile statements.</p>
    <p>&nbsp; We now need to upload the list into the dialog box.&nbsp; So put these lines
    just below the lines you just added.</p>
    <p><small><font face="Courier New">;;;--- Add the layer names to the dialog box<br>
    (start_list &quot;layerlist&quot; 3)<br>
    (mapcar 'add_list layerList)<br>
    (end_list)</font></small></p>
    <p><small><font face="Courier New">;;;--- Add the number of sides to the dialog box<br>
    (start_list &quot;numsides&quot; 3)<br>
    (mapcar 'add_list numSides)<br>
    (end_list)</font></small></p>
    <p><small><font face="Courier New">&nbsp; <strong>When you are done it should look like
    this:</strong></font></small></p>
    <p><font face="Courier New" color="#000000"><small>(defun C:SAMPLE7()<br>
    <br>
    &nbsp; ;;;--- Load the dcl file<br>
    &nbsp; (setq dcl_id (load_dialog &quot;SAMPLE7.dcl&quot;))<br>
    <br>
    &nbsp; ;;;--- Load the dialog definition if it is not already loaded<br>
    &nbsp; (if (not (new_dialog &quot;SAMPLE7&quot; dcl_id) ) (exit))</small></font></p>
    <p><font face="Courier New" color="#FF0000"><small>&nbsp; (setq layerList(list
    &quot;0&quot; &quot;DIM&quot; &quot;HIDDEN&quot; &quot;STR&quot; &quot;TX&quot;
    &quot;WELD&quot;))</small></font></p>
    <p><font face="Courier New" color="#FF0000"><small>&nbsp; (setq numSides(list
    &quot;4&quot; &quot;6&quot; &quot;8&quot; &quot;12&quot; &quot;16&quot;))</small></font></p>
    <p><font face="Courier New" color="#FF0000"><small>&nbsp; ;;;--- Add the layer names to
    the dialog box<br>
    &nbsp; (start_list &quot;layerlist&quot; 3)<br>
    &nbsp; (mapcar 'add_list layerList)<br>
    &nbsp; (end_list)</small></font></p>
    <p><font face="Courier New" color="#FF0000"><small>&nbsp; ;;;--- Add the number of sides
    to the dialog box<br>
    &nbsp; (start_list &quot;numsides&quot; 3)<br>
    &nbsp; (mapcar 'add_list numSides)<br>
    &nbsp; (end_list)</small></font></p>
    <p><font face="Courier New" color="#000000"><small>&nbsp; ;;;--- If an action event
    occurs, do this function<br>
    &nbsp; (action_tile &quot;cancel&quot; &quot;(setq ddiag 1)(done_dialog)&quot;)<br>
    &nbsp; (action_tile &quot;accept&quot; &quot;(setq ddiag 2)(saveVars)(done_dialog)&quot;) <br>
    <br>
    &nbsp; ;;;--- Display the dialog box<br>
    &nbsp; (start_dialog)</small></font></p>
    <p><small><font face="Courier New">&nbsp; ;;;--- Unload the dialog box<br>
    &nbsp; (unload_dialog dcl_id)<br>
    </font><font face="Courier New" color="#000000"><br>
    &nbsp; ;;;--- If the cancel button was pressed - display message<br>
    &nbsp; (if (= ddiag 1)<br>
    &nbsp;&nbsp;&nbsp; (princ &quot;\n \n ...SAMPLE7 Cancelled. \n &quot;)<br>
    &nbsp; )<br>
    <br>
    &nbsp; ;;;--- If the &quot;Okay&quot; button was pressed<br>
    &nbsp; (if (= ddiag 2)<br>
    &nbsp;&nbsp;&nbsp; (princ &quot;\n \n ...SAMPLE7 Complete!&quot;)<br>
    &nbsp; )<br>
    <br>
    &nbsp; ;;;--- Suppress the last echo for a clean exit<br>
    &nbsp; (princ)<br>
    <br>
    ) </font></small></p>
    <hr size="4" color="#0000FF">
    <p><small><font face="Courier New">Save, Load, and Run.&nbsp; You should see this:</font></small></p>
    <p align="center">
    <img src="images/DCL_PART702.jpg" alt="DCL_PART102.jpg (14575 bytes)" WIDTH="368" HEIGHT="185"></p>
    <hr size="4" color="#0000FF">
    <p>Next, let's build the SaveVars routine.&nbsp; We will do this by starting with the
    saveVars routine in the AutoLisp Model, then copy and paste from the &quot;Save Data from
    Dialog Box&quot; section of this tutorial.&nbsp; We will then modify the names to match
    the key names in the DCL file.&nbsp; <em>I also changed a variable name to <font color="#0000FF">numStr</font> to be used later to set the default settings.&nbsp; More on
    that later.</em>&nbsp; I'll show you the changes I made in red:</p>
    <p><small><font face="Courier New">(defun saveVars()</font></small></p>
    <p><small><font face="Courier New">&nbsp; (setq <font color="#FF0000">radios</font>(get_tile
    &quot;<font color="#FF0000">radios</font>&quot;))<br>
    <br>
    &nbsp; ;;;--- Get the number of sides selected from the list<br>
    &nbsp; (setq <font color="#0000FF">numStr</font>(get_tile &quot;<font color="#FF0000">numsides</font>&quot;))<br>
    &nbsp; (if(= <font color="#0000FF">numStr</font> &quot;&quot;)<br>
    &nbsp;&nbsp;&nbsp; (setq <font color="#FF0000">numSides</font> nil)<br>
    &nbsp;&nbsp;&nbsp; (setq <font color="#FF0000">numSides</font>(nth (atoi <font color="#0000FF">numStr</font>) <font color="#FF0000">numSides</font>))<br>
    &nbsp; )<br>
    <br>
    &nbsp; ;;;--- See if the user wants to save the settings<br>
    &nbsp; (setq <font color="#FF0000">saveSet</font>(atoi(get_tile &quot;<font color="#FF0000">saveset</font>&quot;)))<br>
    <br>
    &nbsp; ;;;--- Get the selected item from the layer list<br>
    &nbsp; (setq sStr(get_tile &quot;<font color="#FF0000">layerlist</font>&quot;))<br>
    <br>
    &nbsp; ;;;--- If the index of the selected item is not &quot;&quot; then something was
    selected <br>
    &nbsp; (if(/= sStr &quot;&quot;)<br>
    &nbsp;&nbsp;&nbsp; (progn<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- Something is selected, so convert from string to
    integer<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq sIndex(atoi sStr))<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- And get the selected item from the list<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq <font color="#FF0000">layerName</font>(nth sIndex <font color="#FF0000">layerList</font>))<br>
    &nbsp;&nbsp;&nbsp; )<br>
    <br>
    &nbsp;&nbsp;&nbsp; ;;;--- Else, nothing is selected<br>
    &nbsp;&nbsp;&nbsp; (progn<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- Set the index number to -1<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq sIndex -1)<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- And set the name of the selected item to nil<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq <font color="#FF0000">layerName</font> nil)<br>
    &nbsp;&nbsp;&nbsp; )<br>
    &nbsp; )<br>
    )</font></small>&nbsp;&nbsp;&nbsp; </p>
    <p><strong>Note:</strong>&nbsp; Since we did not specify a default value for the list_box,
    layerName will be set to nil if the user does not select a layer from the list before
    hitting the Okay button.&nbsp; </p>
    <hr size="4" color="#0000FF">
    <p>&nbsp; Save, Load, and Run.&nbsp; Check the values after pressing the Okay button by
    typing an exclamation point and then the variable name on the command line.&nbsp;
    Examples:&nbsp; To get the layer name type <font face="Courier New">!layerName</font> and
    press enter.&nbsp; To get the value of the toggle type <font face="Courier New">!saveSet</font>
    and press enter. &nbsp; Everything working okay?&nbsp; Alrighty then...let's move
    on.&nbsp;&nbsp; </p>
    <hr size="4" color="#0000FF">
    <p>&nbsp; The only work left on the dialog box is to disable the &quot;Number of
    Sides&quot; popup_list when a circle is selected.&nbsp; Let's add two action_tiles on both
    of the radio_buttons.</p>
    <p><font face="Courier New" color="#000000"><small>&nbsp; ;;;--- If an action event
    occurs, do this function<br>
    &nbsp; (action_tile &quot;drawcir&quot; &quot;(toggleRadio 1)&quot;)<br>
    &nbsp; (action_tile &quot;drawpol&quot; &quot;(toggleRadio 2)&quot;) <br>
    </small></font></p>
    <p>&nbsp; This will send a parameter of 1 to the toggleRadio function if the Circle is
    selected.&nbsp; It will send a parameter of 2 to the toggleRadio function if the Polygon
    is selected.&nbsp; What the hell is a toggleRadio function?</p>
    <p>&nbsp; We have to create it and put it in our AutoLisp program.&nbsp; Like this:</p>
    <p><font face="Courier New"><small>(defun toggleRadio(a) </small></font></p>
    <p><font face="Courier New"><small>&nbsp;&nbsp; ;if circle is selected<br>
    &nbsp;&nbsp; (if(= a 1) <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (mode_tile &quot;numsides&quot; 1)&nbsp;&nbsp; ;disable</small></font></p>
    <p><small><font face="Courier New">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;else<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (mode_tile &quot;numsides&quot; 0)&nbsp;&nbsp; ;enable<br>
    &nbsp;&nbsp;&nbsp; )</font> <br>
    <font face="Courier New">)</font></small></p>
    <p><small><font face="Courier New">&nbsp; </font></small>Since our default for the radio
    buttons is to draw a circle, the numSides popup_list should be disabled before the dialog
    box starts.&nbsp; So just before the action_tile statements we need to add this line:</p>
    <p><small><font face="Courier New">(mode_tile &quot;numsides&quot; 1)</font></small></p>
    <p><small><font face="Courier New">&nbsp; Copy, Save, and Run.&nbsp; You should see this:</font></small></p>
    <p align="center">
    <img src="images/DCL_PART703.jpg" alt="DCL_PART103.jpg (13796 bytes)" WIDTH="368" HEIGHT="185"></p>
    <p align="center">
    <img src="images/DCL_PART704.jpg" alt="DCL_PART104.jpg (14378 bytes)" WIDTH="368" HEIGHT="185"></p>
    <p align="left">The numSides popup_list is disabled when the circle is selected. &nbsp;
    Enabled when polygon is selected.&nbsp; Cool.</p>
    <p align="left">Here is the AutoLisp program after the lines above were added:</p>
    <p align="left"><small><font face="Courier New">(defun saveVars()<br>
    &nbsp; (setq radios(get_tile &quot;radios&quot;))<br>
    <br>
    &nbsp; ;;;--- Get the number of sides selected from the list<br>
    &nbsp; (setq sStr(get_tile &quot;numsides&quot;))<br>
    &nbsp; (if(= sStr &quot;&quot;)<br>
    &nbsp;&nbsp;&nbsp; (setq numSides nil)<br>
    &nbsp;&nbsp;&nbsp; (setq numSides(nth (atoi sStr) numSides))<br>
    &nbsp; )<br>
    <br>
    &nbsp; ;;;--- See if the user wants to save the settings<br>
    &nbsp; (setq saveSet(atoi(get_tile &quot;saveset&quot;)))<br>
    <br>
    &nbsp; ;;;--- Get the selected item from the layer list<br>
    &nbsp; (setq sStr(get_tile &quot;layerlist&quot;))<br>
    <br>
    &nbsp; ;;;--- If the index of the selected item is not &quot;&quot; then something was
    selected <br>
    &nbsp; (if(/= sStr &quot;&quot;)<br>
    &nbsp;&nbsp;&nbsp; (progn<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- Something is selected, so convert from string to
    integer<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq sIndex(atoi sStr))<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- And get the selected item from the list<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq layerName(nth sIndex layerList))<br>
    &nbsp;&nbsp;&nbsp; )<br>
    <br>
    &nbsp;&nbsp;&nbsp; ;;;--- Else, nothing is selected<br>
    &nbsp;&nbsp;&nbsp; (progn<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- Set the index number to -1<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq sIndex -1)<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- And set the name of the selected item to nil<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq layerName nil)<br>
    &nbsp;&nbsp;&nbsp; )<br>
    &nbsp; )<br>
    )<br>
    <br>
    <font color="#FF0000">(defun toggleRadio(a) <br>
    </font><font color="#000000">&nbsp;&nbsp; ;if circle is selected</font><font color="#FF0000"><br>
    &nbsp;&nbsp; (if(= a 1) <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (mode_tile &quot;numsides&quot; 1) ;disable<br>
    </font><font color="#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;else</font><font color="#FF0000"><br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (mode_tile &quot;numsides&quot; 0) ;enable<br>
    &nbsp;&nbsp;&nbsp; ) <br>
    )</font><br>
    <br>
    (defun C:SAMPLE7()<br>
    <br>
    &nbsp; ;;;--- Load the dcl file<br>
    &nbsp; (setq dcl_id (load_dialog &quot;SAMPLE7.dcl&quot;))<br>
    <br>
    &nbsp; ;;;--- Load the dialog definition if it is not already loaded<br>
    &nbsp; (if (not (new_dialog &quot;SAMPLE7&quot; dcl_id) ) (exit))<br>
    <br>
    &nbsp; (setq layerList(list &quot;0&quot; &quot;DIM&quot; &quot;HIDDEN&quot;
    &quot;STR&quot; &quot;TX&quot; &quot;WELD&quot;))<br>
    &nbsp; (setq numSides(list &quot;4&quot; &quot;6&quot; &quot;8&quot; &quot;12&quot;
    &quot;16&quot;))<br>
    <br>
    &nbsp; ;;;--- Add the layer names to the dialog box<br>
    &nbsp; (start_list &quot;layerlist&quot; 3)<br>
    &nbsp; (mapcar 'add_list layerList)<br>
    &nbsp; (end_list)<br>
    <br>
    &nbsp; ;;;--- Add the number of sides to the dialog box<br>
    &nbsp; (start_list &quot;numsides&quot; 3)<br>
    &nbsp; (mapcar 'add_list numSides)<br>
    &nbsp; (end_list)<br>
    <br>
    &nbsp; <font color="#FF0000">(mode_tile &quot;numsides&quot; 1)</font><br>
    <br>
    &nbsp; ;;;--- If an action event occurs, do this function<br>
    <font color="#FF0000">&nbsp; (action_tile &quot;drawcir&quot; &quot;(toggleRadio 1)&quot;)<br>
    &nbsp; (action_tile &quot;drawpol&quot; &quot;(toggleRadio 2)&quot;)</font><br>
    &nbsp; (action_tile &quot;cancel&quot; &quot;(setq ddiag 1)(done_dialog)&quot;)<br>
    &nbsp; (action_tile &quot;accept&quot; &quot;(setq ddiag 2)(saveVars)(done_dialog)&quot;) <br>
    <br>
    &nbsp; ;;;--- Display the dialog box<br>
    &nbsp; (start_dialog)</font></small></p>
    <p align="left"><small><font face="Courier New">&nbsp; ;;;--- Unload the dialog box<br>
    &nbsp; (unload_dialog dcl_id)<br>
    <br>
    &nbsp; ;;;--- If the cancel button was pressed - display message<br>
    &nbsp; (if (= ddiag 1)<br>
    &nbsp;&nbsp;&nbsp; (princ &quot;\n \n ...SAMPLE7 Cancelled. \n &quot;)<br>
    &nbsp; )<br>
    <br>
    &nbsp; ;;;--- <strong>If the &quot;Okay&quot; button was pressed</strong><br>
    &nbsp; (if (= ddiag 2)<br>
    &nbsp;&nbsp;&nbsp; <font color="#0000FF">(princ &quot;\n \n ...SAMPLE7 Complete!&quot;)</font><br>
    &nbsp; )<br>
    <br>
    &nbsp; ;;;--- Suppress the last echo for a clean exit<br>
    &nbsp; (princ)<br>
    <br>
    )</font></small></p>
    <hr size="4" color="#0000FF">
    <p>&nbsp; Now the only thing remaining is to do something when the user presses the okay
    button.&nbsp; We have all of the dialog box data stored in variable names....</p>
    <table border="1" width="100%">
      <tr>
        <td width="25%" align="center"><strong>Variable Name</strong></td>
        <td width="25%" align="center"><strong>DCL Control Item</strong></td>
        <td width="22%" align="center"><strong>Action Key</strong></td>
        <td width="28%" align="center"><strong>Type of Data Stored</strong></td>
      </tr>
      <tr>
        <td width="25%" align="center">radios</td>
        <td width="25%" align="center">Radio_Column</td>
        <td width="22%" align="center">&quot;radios&quot;</td>
        <td width="28%" align="center">String [ Action Key Name]</td>
      </tr>
      <tr>
        <td width="25%" align="center">numSides</td>
        <td width="25%" align="center">Popup_List</td>
        <td width="22%" align="center">&quot;numsides&quot;</td>
        <td width="28%" align="center">Integer [ Number of sides]</td>
      </tr>
      <tr>
        <td width="25%" align="center">saveSet</td>
        <td width="25%" align="center">Toggle</td>
        <td width="22%" align="center">&quot;saveset&quot;</td>
        <td width="28%" align="center">Integer [ 0 or 1 ]</td>
      </tr>
      <tr>
        <td width="25%" align="center">layerName</td>
        <td width="25%" align="center">List</td>
        <td width="22%" align="center">&quot;layerlist&quot;</td>
        <td width="28%" align="center">String [ Name of Layer]</td>
      </tr>
    </table>
    <p>&nbsp;&nbsp; So now all we have to do is write the AutoLisp code inside the &quot;Okay
    button was pressed&quot; IF statement.&nbsp; (Where the blue line is above.)</p>
    <hr size="4" color="#0000FF">
    <p>&nbsp; Now we will replace the blue line above: <font face="Courier New" color="#0000FF"><small>(princ &quot;\n \n ...SAMPLE Complete!&quot;) </small></font><font color="#000000">with new code.</font></p>
    <p><font color="#000000">&nbsp; First, let's go ahead and change the layer.</font></p>
    <p><font face="Courier New" color="#FF0000"><small>(setq oldLay(getvar
    &quot;clayer&quot;)) <br>
    (setvar &quot;clayer&quot; layerName)</small></font></p>
    <p><font color="#000000">&nbsp; That was easy.&nbsp; Now,&nbsp; Let's draw the selected
    entity</font></p>
    <p><small><font face="Courier New" color="#FF0000">(if(= radios &quot;drawcir&quot;)<br>
    &nbsp; (progn<br>
    &nbsp;&nbsp;&nbsp; (setq pt(getpoint &quot;\n Center point: &quot;))<br>
    &nbsp;&nbsp;&nbsp; (command &quot;circle&quot; pt pause)<br>
    &nbsp; )<br>
    </font><font face="Courier New" color="#000000">&nbsp; ;;;--- Else draw a polygon</font><font face="Courier New" color="#FF0000"><br>
    &nbsp; (progn<br>
    &nbsp;&nbsp;&nbsp; (setq pt(getpoint &quot;\n Center Point: &quot;))<br>
    &nbsp;&nbsp;&nbsp; (command &quot;polygon&quot; numSides pt &quot;C&quot; pause)<br>
    &nbsp; )<br>
    )</font></small></p>
    <p><font color="#000000">Add the above to your program and save it.&nbsp; Test it out.
    &nbsp; Everything working okay?</font></p>
    <hr size="4" color="#0000FF">
    <p><font color="#000000">&nbsp; And finally all we have left is the code for the default
    settings.&nbsp; Since everything in the dialog box is a string, why don't we save all of
    the data as strings.&nbsp; Lucky for us, AutoDesk included 15 setvars for us to store data
    in.&nbsp; USERR1 thru USERR5 is used to store real numbers.&nbsp; USERI1 thru USERI5 is
    used to store integers.&nbsp; USERS1 thru USERS5 are used to store strings.&nbsp; We will
    use the system variables USERS1 thru USERS4 to save our data since we are saving the data
    as strings.&nbsp; All of these setvars are stored inside the drawing file.&nbsp; They will
    be there everytime you open your drawing.&nbsp; How convenient!&nbsp; So let's get to it.</font></p>
    <p><font color="#000000">&nbsp; The first variable to store is RADIOS and it is already a
    string.&nbsp; So....</font></p>
    <p><font face="Courier New" color="#FF0000">(setvar &quot;USERS1&quot; radios)</font></p>
    <p><font color="#000000">&nbsp; The second variable to store is NUMSIDES and it is an
    integer representing the number of sides the polygon should have.&nbsp; I want to store
    the index of the selected item in the list not the actual number of sides.&nbsp; We saved
    the index as a variable named NUMSTR when we ran the saveVars routine.&nbsp; So...</font></p>
    <p><font face="Courier New" color="#FF0000">(setvar &quot;USERS2&quot; numStr)</font></p>
    <p><font color="#000000">&nbsp; The third variable to save is SAVESET.&nbsp; It is stored
    as an integer.&nbsp; We will have to convert it to a string to save it.</font></p>
    <p><font face="Courier New" color="#FF0000">(setvar &quot;USERS3&quot; (itoa saveSet))</font></p>
    <p><font color="#000000">&nbsp; The fourth and final variable to save is LAYERNAME. &nbsp;
    It is stored as a string.&nbsp; I want to save the index of the selected item. &nbsp; We
    saved that earlier with the saveVars routine in a variable named sSTR.</font></p>
    <p><font face="Courier New" color="#FF0000">(setvar &quot;USERS4&quot; sSTR)</font></p>
    <p>&nbsp;</p>
    <p><font color="#000000">&nbsp; The last thing we have to do is check for the default
    settings and load them if they exist.</font></p>
    <p><small><font face="Courier New">(defun saveVars()</font></small></p>
    <p><small><font face="Courier New">&nbsp; (setq radios(get_tile &quot;radios&quot;))<br>
    <br>
    &nbsp; ;;;--- Get the number of sides selected from the list<br>
    &nbsp; (setq numStr(get_tile &quot;numsides&quot;))<br>
    &nbsp; (if(= numStr &quot;&quot;)<br>
    &nbsp;&nbsp;&nbsp; (setq numSides nil)<br>
    &nbsp;&nbsp;&nbsp; (setq numSides(nth (atoi numStr) numSides))<br>
    &nbsp; )<br>
    <br>
    &nbsp; ;;;--- See if the user wants to save the settings<br>
    &nbsp; (setq saveSet(atoi(get_tile &quot;saveset&quot;)))<br>
    <br>
    &nbsp; ;;;--- Get the selected item from the layer list<br>
    &nbsp; (setq sStr(get_tile &quot;layerlist&quot;))<br>
    <br>
    &nbsp; ;;;--- If the index of the selected item is not &quot;&quot; then something was
    selected <br>
    &nbsp; (if(/= sStr &quot;&quot;)<br>
    &nbsp;&nbsp;&nbsp; (progn<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- Something is selected, so convert from string to
    integer<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq sIndex(atoi sStr))<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- And get the selected item from the list<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq layerName(nth sIndex layerList))<br>
    &nbsp;&nbsp;&nbsp; )<br>
    <br>
    &nbsp;&nbsp;&nbsp; ;;;--- Else, nothing is selected<br>
    &nbsp;&nbsp;&nbsp; (progn<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- Set the index number to -1<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq sIndex -1)<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- And set the name of the selected item to nil<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq layerName nil)<br>
    &nbsp;&nbsp;&nbsp; )<br>
    &nbsp; )<br>
    )<br>
    <br>
    (defun toggleRadio(a) <br>
    &nbsp;&nbsp; ;if circle is selected<br>
    &nbsp;&nbsp; (if(= a 1) <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (mode_tile &quot;numsides&quot; 1) ;disable<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;else<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (mode_tile &quot;numsides&quot; 0) ;enable<br>
    &nbsp;&nbsp;&nbsp; ) <br>
    )<br>
    <br>
    <font color="#0000FF">(defun C:SAMPLE7()</font><br>
    <br>
    &nbsp; ;;;--- Load the dcl file<br>
    &nbsp; (setq dcl_id (load_dialog &quot;SAMPLE7.dcl&quot;))<br>
    <br>
    &nbsp; ;;;--- Load the dialog definition if it is not already loaded<br>
    &nbsp; (if (not (new_dialog &quot;SAMPLE7&quot; dcl_id) ) (exit))<br>
    </font></small></p>
    <p><small><font face="Courier New">&nbsp; ;;; Build the list for the dialog box</font></small>
    <br>
    <small><font face="Courier New">&nbsp; (setq layerList(list &quot;0&quot; &quot;DIM&quot;
    &quot;HIDDEN&quot; &quot;STR&quot; &quot;TX&quot; &quot;WELD&quot;))<br>
    &nbsp; (setq numSides(list &quot;4&quot; &quot;6&quot; &quot;8&quot; &quot;12&quot;
    &quot;16&quot;))<br>
    <br>
    &nbsp; ;;;--- Add the layer names to the dialog box<br>
    &nbsp; (start_list &quot;layerlist&quot; 3)<br>
    &nbsp; (mapcar 'add_list layerList)<br>
    &nbsp; (end_list)<br>
    <br>
    &nbsp; ;;;--- Add the number of sides to the dialog box<br>
    &nbsp; (start_list &quot;numsides&quot; 3)<br>
    &nbsp; (mapcar 'add_list numSides)<br>
    &nbsp; (end_list)<br>
    <br>
    <br>
    &nbsp; ;;;--- Add the code here to check for defaults<br>
    &nbsp; <font color="#FF0000">(if(/= (getvar &quot;USERS1&quot;) &quot;&quot;)<br>
    &nbsp;&nbsp;&nbsp; (progn<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq radios (getvar &quot;users1&quot;))<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq numStr (getvar &quot;users2&quot;))<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq saveSet(getvar &quot;users3&quot;))<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq layerIndex(getvar &quot;users4&quot;))<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (set_tile &quot;radios&quot; radios)<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (set_tile &quot;numsides&quot; numStr)<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (set_tile &quot;saveset&quot; saveSet)<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (set_tile &quot;layerlist&quot; layerIndex)<br>
    &nbsp;&nbsp;&nbsp; )<br>
    &nbsp; )</font><br>
    </font></small></p>
    <p><small><font face="Courier New">&nbsp; ;;;--- Only disable the numSides popup_list if a
    circle is being drawn<br>
    &nbsp; <font color="#FF0000">(if(= radios &quot;drawcir&quot;)</font><br>
    &nbsp;&nbsp;&nbsp; (mode_tile &quot;numsides&quot; 1)<br>
    &nbsp; <font color="#FF0000">)</font><br>
    <br>
    &nbsp; ;;;--- If an action event occurs, do this function<br>
    &nbsp; (action_tile &quot;drawcir&quot; &quot;(toggleRadio 1)&quot;)<br>
    &nbsp; (action_tile &quot;drawpol&quot; &quot;(toggleRadio 2)&quot;)<br>
    &nbsp; (action_tile &quot;cancel&quot; &quot;(setq ddiag 1)(done_dialog)&quot;)<br>
    &nbsp; (action_tile &quot;accept&quot; &quot;(setq ddiag 2)(saveVars)(done_dialog)&quot;) <br>
    <br>
    &nbsp; ;;;--- Display the dialog box<br>
    &nbsp; (start_dialog)</font></small></p>
    <p><small><font face="Courier New">&nbsp; ;;;--- Unload the dialog box<br>
    &nbsp; (unload_dialog dcl_id)<br>
    <br>
    &nbsp; ;;;--- If the cancel button was pressed - display message<br>
    &nbsp; (if (= ddiag 1)<br>
    &nbsp;&nbsp;&nbsp; (princ &quot;\n \n ...SAMPLE7 Cancelled. \n &quot;)<br>
    &nbsp; )<br>
    <br>
    &nbsp; ;;;--- If the &quot;Okay&quot; button was pressed<br>
    &nbsp; (if (= ddiag 2)<br>
    &nbsp;&nbsp;&nbsp; <font color="#FF0000">(progn</font><br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- Save the old layer and reset to new layer<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color="#FF0000">(setq oldLay(getvar
    &quot;clayer&quot;)) <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setvar &quot;clayer&quot; layerName)<br>
    </font></font></small></p>
    <p><small><font face="Courier New" color="#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;---
    See what needs to be drawn<br>
    </font><font color="#FF0000" face="Courier New">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (if(=
    radios &quot;drawcir&quot;)<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (progn<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq pt(getpoint &quot;\n Center
    point: &quot;))<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (command &quot;circle&quot; pt
    pause)<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; )</font></small></p>
    <p><small><font face="Courier New">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- Else
    draw a polygon<br>
    <font color="#FF0000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (progn<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setq pt(getpoint &quot;\n Center
    Point: &quot;))<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (command &quot;polygon&quot;
    numSides pt &quot;C&quot; pause)<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; )<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; )</font><br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- See if we need to save the settings<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color="#FF0000">(if(= saveSet 1)<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (progn</font><br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;;;--- Add code here to save the
    settings as defaults<br>
    &nbsp;<font color="#FF0000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setvar
    &quot;USERS1&quot; radios)<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setvar &quot;USERS2&quot; numStr)<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setvar &quot;USERS3&quot; (itoa
    saveSet))<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (setvar &quot;USERS4&quot; sSTR)<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; )<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; )</font><br>
    &nbsp;&nbsp;&nbsp;<font color="#FF0000"> )</font><br>
    &nbsp; )<br>
    <br>
    &nbsp; ;;;--- Suppress the last echo for a clean exit<br>
    &nbsp; (princ)<br>
    <br>
    )</font></small></p>
    <p>&nbsp; When you get your program tested and everything is working, move the blue line
    above, [ <font color="#0000FF" face="Courier New"><small>(defun C:SAMPLE7()</small></font>
    ] all the way to the top of the file.&nbsp; This will make all of your variables local and
    will reset them all to nil when the program ends.</p>
    <p>&nbsp; That's it.&nbsp; We're done.</p>
    <p align="center"><a href="autolisp_DCL.html">Back</a></p>
    <hr size="4" color="#0000FF">
    <p align="center"><a href="index.html">AutoLisp Tutorial Home</a></p>
</body>

</html>
