<html>


<!-- Mirrored from www.jefferypsanders.com/autolispintr_sele.html by HTTrack Website Copier/3.x [XR&CO'2004], Thu, 23 Sep 2004 01:07:54 GMT -->
<head>
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="description" content="Autolisp Entity Selection Functions.">
<meta name="keywords" content="autolisp selection, autolisp entity selection, autolisp programming, entsel, ssget, example program">
<title>The AutoLisp Intermediate Tutorial - Selecting Entities</title>
</head>

<body>

<p align="center"><font color="#000000"><big><big><big><strong>The
    AutoLisp Intermediate Tutorial</strong></big></big></big></font><font face="Helvetica"></p>
    </font><hr size="4" color="#0000FF">
    <p align="left"><u><big><big><strong>Selecting Entities</strong></big></big></u></p>
    <p align="left"><big>Functions&nbsp; -&nbsp;&nbsp;&nbsp; <a href="#entsel">entsel </a>&nbsp;&nbsp;&nbsp;
    <a href="#ssget">ssget</a>&nbsp;&nbsp;&nbsp; <a href="#Example">Example Programs</a></big></p>
    <hr size="4" color="#0000FF">
    <p align="left"><a name="entsel"><big><strong>entsel</strong></big></a> - This function
    prompts for the user to pick one entity.&nbsp;&nbsp;&nbsp; </p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Syntax : <strong>(entsel)</strong></p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <strong>Returns</strong> the entity's name and the point selected in a list. </p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Example: (&lt;Entity name: 3b40a08&gt; (230.666 285.862 0.0))</p>
    <p align="left"><br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font color="#FF0000" face="Courier">(car(entsel))</font> returns the entity name if entsel does
    not return nil..</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(cadr(entsel))</font> returns the point selected if
    entsel does not return nil..</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Note: Selecting an area in the drawing where there are no entities would return nil.&nbsp;
    You will get an error
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    if you try to get the car or cadr of nil as shown above.&nbsp; The best thing to do is to
    save the return value of
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    the entsel function, then check to see if it is a valid selection.&nbsp; </p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Example:</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <font color="#FF0000" face="Courier">(setq myEnt(entsel))
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </font><font color="#000000">; save
    the return value of the entsel function</font></p>
    <p align="left"><font color="#FF0000" face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    (if myEnt
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </font><font color="#000000">; if the value of myEnt is not nil then do some stuff</font><font color="#FF0000" face="Courier">&nbsp; </font></p>
    <p align="left"><font color="#FF0000" face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    (progn </font><font color="#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ; use the progn statement here for multiple statements</font></p>
    <p align="left"><font color="#FF0000" face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;do some stuff&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </font><font color="#000000">; put your code here</font></p>
    <p align="left"><font color="#FF0000" face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    )&nbsp; </font><font color="#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ; close the progn statement here</font></p>
    <p align="left"><font color="#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </font><font color="#FF0000" face="Courier">(alert &quot;Nothing Selected.&quot;)&nbsp; </font><font color="#000000">; alert the user</font></p>
    <p align="left"><font color="#FF0000" face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    )
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </font><font color="#000000">; close the if statement</font><font color="#FF0000" face="Courier"> </font></p>
    <p align="left">&nbsp;</p>
    <p align="left"><a name="ssget"><big><strong>ssget</strong></big> </a>- This function
    prompts the user to select entities.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Syntax &nbsp; :&nbsp; <strong>(ssget)&nbsp;&nbsp;&nbsp; </strong>;prompts the user for a
    selection set.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Syntax &nbsp; :&nbsp; <strong>(ssget mode)&nbsp;&nbsp;&nbsp; </strong>;prompts the user
    for a selection set and sets mode to &quot;W&quot;, &quot;C&quot;, &quot;L&quot;, and
    &quot;P&quot;,
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    corresponding to the Window, Crossing, Last, and Previous selection methods. Another
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    optional mode value is &quot;X&quot;, which selects the entire database.&nbsp; There are
    other modes, but this
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    list contains the modes that will be used most often.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Syntax &nbsp; :&nbsp; <strong>(ssget &quot;W&quot; )&nbsp;&nbsp;&nbsp; </strong>;prompts
    the user for a selection set using the Window mode.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Syntax &nbsp; :&nbsp; <strong>(ssget &quot;C&quot; )&nbsp;&nbsp;&nbsp; </strong>;prompts
    the user for a selection set using the Crossing mode.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Syntax &nbsp; :&nbsp; <strong>(ssget &quot;L&quot; )&nbsp;&nbsp;&nbsp; </strong>;Selects
    the last entity selected.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Syntax &nbsp; :&nbsp; <strong>(ssget &quot;P&quot; )&nbsp;&nbsp;&nbsp; </strong>;Selects
    the previously selected entities.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Syntax &nbsp; :&nbsp; <strong>(ssget &quot;X&quot; )&nbsp;&nbsp;&nbsp; </strong>;Selects
    all entities in the drawing.</p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Syntax &nbsp; :&nbsp; <strong>(ssget filter_List)&nbsp; or (ssget mode filter_List)</strong></p>
    <p align="left"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    filter_List </strong>- an association list containing valid filters for entities
    corresponding to the Entity DXF Group
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Codes. &nbsp;&nbsp;&nbsp; What did I just say?&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Entity DXF Group Codes?&nbsp;&nbsp; What the heck is that?
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Click <a href="autolispintr_dxf.html">here</a> to find out.&nbsp; </p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    You can filter out enitites that do no match your criteria using the filter_List.&nbsp; If
    you only
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    wanted entities that were on layer &quot;STR&quot; then you could add a filter list that
    looks like this:</p>
    <p align="left"><font color="#FF0000" face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    (setq myFilter(list (cons 8 &quot;STR&quot;))) </font><font color="#000000">;returns <font face="Courier">((8 . &quot;STR&quot;))</font></font></p>
    <p align="left"><font color="#FF0000" face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    (ssget &quot;X&quot; myFilter)&nbsp; </font><font color="#000000">;returns a selection set
    containing only entities on layer &quot;STR&quot;</font></p>
    <p align="left"><font color="#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    or</font></p>
    <p align="left"><font color="#FF0000" face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    (setq myFilter(list (cons 0 &quot;LINE&quot;)(cons 8 &quot;STR&quot;))) </font></p>
    <p align="left"><font color="#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;returns <font face="Courier">((0 . &quot;LINE&quot;)(8 . &quot;STR&quot;))</font></font></p>
    <p align="left"><font color="#FF0000" face="Courier">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    (ssget &quot;X&quot; myFilter)&nbsp; </font></p>
    <p align="left"><font color="#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;returns a selection set containing only line entities on layer &quot;STR&quot;</font></p>
    <p align="left"><font color="#000000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </font></p>
    <p align="left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <strong>Returns</strong> a selection set of entity names.</p>
    <p align="left"><strong>End of Selecting Entities</strong></p>
    <hr size="4" color="#0000FF">
    <p><strong><a name="Example">Example</a> Program 1:</strong></p>
    <p><font face="Courier">(defun C:myProg()</font></p>
    <p><font face="Courier">&nbsp; (if (setq myEnt(entsel))
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;start the if
    statement </font></p>
    <p><font face="Courier">&nbsp;&nbsp; (progn
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;going to have multiple statements</font></p>
    <p><font face="Courier">&nbsp; &nbsp; (setq pt1(getpoint &quot;\n Base Point: &quot;))
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;store base point</font></p>
    <p><font face="Courier">&nbsp;&nbsp;&nbsp; (setq pt2(getpoint &quot;\n Displacement Point:
    &quot;))&nbsp;&nbsp;&nbsp;&nbsp; ;store displacement pt&nbsp; </font></p>
    <p><font face="Courier">&nbsp;&nbsp;&nbsp; (command &quot;move&quot; (car myEnt)
    &quot;&quot; pt1 pt2) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;move entity </font></p>
    <p><font face="Courier">&nbsp;&nbsp; )
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;close the progn</font></p>
    <p><font face="Courier">&nbsp;&nbsp; (alert &quot;Please select an entity!&quot;)
    &nbsp;&nbsp; ;else alert the user of an error</font></p>
    <p><font face="Courier">&nbsp; )
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;close the if statement</font></p>
    <p><font face="Courier">&nbsp; (princ)
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;clean exit (supresses echo)</font></p>
    <p><font face="Courier">)
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;close the program</font></p>
    <p><strong><font face="Courier">Execution:</font></strong></p>
    <p><font face="Courier">Command: (load &quot;myProg&quot;)&lt;enter&gt;</font></p>
    <p><font face="Courier">Command: myProg&lt;enter&gt;</font></p>
    <p><font face="Courier">Command: Select Object: &lt;pick&gt;</font></p>
    <p><font face="Courier">Command: Base Point: &lt;pick&gt;</font></p>
    <p><font face="Courier">Command: Displacement Point: &lt;pick&gt;</font></p>
    <p><font face="Courier">Command:</font></p>
    <hr size="4" color="#0000FF">
    <p><strong>Example Program 2:</strong></p>
    <p><font face="Courier">(defun C:myProg2()</font></p>
    <p><font face="Courier">&nbsp; (if (setq mySet(ssget &quot;X&quot; (list (cons 8
    &quot;STR&quot;)(cons 0 &quot;CIRCLE&quot;)))) ;get set </font></p>
    <p><font face="Courier">&nbsp;&nbsp; (progn
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;going to have multiple statements</font></p>
    <p><font face="Courier">&nbsp; &nbsp; (setq pt1(getpoint &quot;\n Base Point: &quot;))
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ;store base point</font></p>
    <p><font face="Courier">&nbsp;&nbsp;&nbsp; (setq pt2(getpoint &quot;\n Displacement Point:
    &quot;))&nbsp;&nbsp;&nbsp;&nbsp; ;store displacement pt&nbsp; </font></p>
    <p><font face="Courier">&nbsp;&nbsp;&nbsp; (command &quot;move&quot; mySet &quot;&quot;
    pt1 pt2)&nbsp;&nbsp; ;move all entities </font></p>
    <p><font face="Courier">&nbsp;&nbsp; )
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;close the progn</font></p>
    <p><font face="Courier">&nbsp;&nbsp; (alert &quot;No entites Match Criteria!&quot;) ;else
    alert the user of an error</font></p>
    <p><font face="Courier">&nbsp; )
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;close the if statement</font></p>
    <p><font face="Courier">&nbsp; (princ)
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;clean exit (supresses echo)</font></p>
    <p><font face="Courier">)
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    ;close the program</font></p>
    <p><strong><font face="Courier">Execution:</font></strong></p>
    <p><font face="Courier">Command: (load &quot;myProg2&quot;)&lt;enter&gt;</font></p>
    <p><font face="Courier">Command: myProg2&lt;enter&gt;</font></p>
    <p><font face="Courier">Command: Base Point: &lt;pick&gt;</font></p>
    <p><font face="Courier">Command: Displacement Point: &lt;pick&gt;</font></p>
    <p><font face="Courier">Command:</font></p>
    <hr size="4" color="#0000FF">
    <p align="center"><a href="autolispintr.html">AutoLisp Intermediate Tutorial</a></p>
    <p align="center"><a href="index.html">AutoLisp Tutorial Home</a></p>
</body>

</html>
